FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-slim

WORKDIR /app
COPY --from=builder /app /app

EXPOSE 3000

ENV NODE_ENV=production
CMD ["npm", "start"]
